-- 코드를 입력하세요
SELECT MEMBER_ID, MEMBER_NAME, GENDER, convert(DATE, DATE_OF_BIRTH, 102) FROM MEMBER_PROFILE
WHERE DATE_OF_BIRTH IS LIKE '%-03-%'
AND TLNO IS NOT NULL
AND GENDER = "W"
ORDER BY MEMBER_ID DESC
